version: '3.8'
services:
  primary1:
    image: postgres:latest
    container_name: pmaster
    ports:
      - "5432:5432"
    volumes:
      - D:/mini youtube/rep/pmaster_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main_database
    restart: always

  replica1:
    image: postgres:latest
    container_name: pstandby
    ports:
      - "5433:5432"
    volumes:
      - D:/mini youtube/rep/pstandby_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # POSTGRES_DB: secondryDB
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: my-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - primary1
    restart: always

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  kafkaA:
    image: wurstmeister/kafka:latest
    container_name: kafkaA
    ports:
      - "9096:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafkaA:9092,OUTSIDE://localhost:9096
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9096
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - kafka-network

  # kafkaB:
  #   image: wurstmeister/kafka:latest
  #   container_name: kafkaB
  #   ports:
  #     - "9097:9093"
  #   environment:
  #     KAFKA_ADVERTISED_LISTENERS: INSIDE://kafkaB:9093,OUTSIDE://localhost:9093
  #     KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9093
  #     KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #   networks:
  #     - kafka-network


  

  

  # kafka-1:
  #   image: wurstmeister/kafka:latest
  #   container_name: kafka1
  #   environment:
  #     KAFKA_LISTENER_NAME: PLAINTEXT
  #     KAFKA_LISTENERS: PLAINTEXT://kafka-1:9092
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
  #     KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
  #     KAFKA_MODE: KRAFT
  #     KAFKA_KRAFT_MODE: 'true'
  #     KAFKA_PROCESS_ROLES: broker
  #   ports:
  #     - "9092:9092"


  # kafka-2:
  #   image: wurstmeister/kafka:latest
  #   container_name: kafka2
  #   environment:
  #     KAFKA_LISTENER_NAME: PLAINTEXT
  #     KAFKA_LISTENERS: PLAINTEXT://kafka-2:9092
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
  #     KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
  #     KAFKA_MODE: KRAFT
  #     KAFKA_KRAFT_MODE: 'true'
  #     KAFKA_PROCESS_ROLES: broker
  #   ports:
  #     - "9093:9092"

  

  minio:
    image: quay.io/minio/minio
    container_name: minio1
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ROOTUSER
      MINIO_ROOT_PASSWORD: CHANGEME123
    volumes:
      - D:\minio\data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

   
networks:
  kafka-network:
    driver: bridge

# volumes:
#   pmaster_data:
#     driver: local
#   pstandby_data:
#     driver: local
#   minio-data:
#     driver: local
  

