version: '3.8'

services:
  node-app:
    build: .
    container_name: mini-youtube
    ports:
      - '8000:8000'
    volumes:
      - ./src:/app/src:ro
    environment:
      - PORT=8000
    networks:
      - shared-network


networks:
  shared-network:
    external: true
    name: kafkaimage-kafkanet