version: '3.8'

services:
  nginx-x:
    image: nginx:latest
    container_name: ngnixx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - shared-network



networks:
  shared-network:
    external: true
    name: network1
