version: '3.8'

services:

  primary1:
      image: postgres:latest
      container_name: pmaster
      ports:
        - "5432:5432"
      volumes:
        - D:/mini youtube/rep/pmaster_data:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: main_database
      restart: always
      networks:
        - shared-network
  replica1:
    image: postgres:latest
    container_name: pstandby
    ports:
      - "5433:5432"
    volumes:
      - D:/mini youtube/rep/pstandby_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main_database
    restart: always
    networks:
      - shared-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: my-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - primary1
    restart: always
    networks:
    - shared-network



networks:
  shared-network:
    external: true
    name: kafkaimage-kafkanet    